import type { ControlDefinition, SealConfig, TemplateId, TemplatePreset } from './types'

const SONG_FONT = "'STZhongsong', 'Songti SC', 'SimSun', 'STSong', serif"
const FANG_SONG_FONT = "'STFangsong', 'FangSong', 'FangSong_GB2312', serif"
const ARIAL_FONT = "'Arial', 'Helvetica Neue', sans-serif"

/** 按规范中的“字边线到内边距离”换算当前渲染器所需的文字中心内缩。 */
function getSpecTopTextInsetMm(borderWidthMm: number, fontSizeMm: number, edgeDistanceMm: number) {
  return borderWidthMm / 2 + edgeDistanceMm + fontSizeMm / 2
}

/** 按规范的字中心距离 2mm 反推当前编码的默认字距。 */
function getSpecCodeLetterSpacingMm(fontSizeMm: number) {
  const glyphWidthMm = fontSizeMm * (5 / 6)
  return Math.max(2 - glyphWidthMm, 0)
}

const baseControls: ControlDefinition[] = [
  {
    key: 'color',
    label: '印章颜色',
    section: '导出参数',
    kind: 'color',
    help: '用于描边与文字的统一颜色。',
  },
  {
    key: 'exportScale',
    label: '导出像素倍率',
    section: '导出参数',
    kind: 'number',
    min: 8,
    max: 40,
    step: 1,
    help: '每毫米对应的输出像素数，数值越高导出越清晰。',
  },
  {
    key: 'widthMm',
    label: '印章宽度(mm)',
    section: '结构参数',
    kind: 'number',
    min: 20,
    max: 80,
    step: 0.1,
  },
  {
    key: 'heightMm',
    label: '印章高度(mm)',
    section: '结构参数',
    kind: 'number',
    min: 20,
    max: 80,
    step: 0.1,
  },
  {
    key: 'borderWidthMm',
    label: '边框宽度(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0.4,
    max: 4,
    step: 0.1,
  },
  {
    key: 'topText',
    label: '上环文字',
    section: '文本内容',
    kind: 'text',
    placeholder: '请输入单位名称',
  },
  {
    key: 'topTextFontFamily',
    label: '上环字体族',
    section: '字体参数',
    kind: 'text',
    placeholder: SONG_FONT,
  },
  {
    key: 'topTextFontSizeMm',
    label: '上环字号(mm)',
    section: '字体参数',
    kind: 'number',
    min: 2,
    max: 10,
    step: 0.1,
  },
  {
    key: 'topTextInsetMm',
    label: '上环内缩(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0.5,
    max: 10,
    step: 0.1,
    help: '指文字中心相对外边线向内收缩的距离。',
  },
  {
    key: 'topTextAngleDeg',
    label: '上环夹角(度)',
    section: '结构参数',
    kind: 'number',
    min: 120,
    max: 300,
    step: 1,
  },
]

const starControls: ControlDefinition[] = [
  {
    key: 'centerSymbolSizeMm',
    label: '五角星直径(mm)',
    section: '结构参数',
    kind: 'number',
    min: 4,
    max: 20,
    step: 0.1,
  },
  {
    key: 'centerSymbolOffsetYMm',
    label: '五角星上移(mm)',
    section: '结构参数',
    kind: 'number',
    min: -5,
    max: 5,
    step: 0.1,
  },
]

const bottomTextControls: ControlDefinition[] = [
  {
    key: 'bottomText',
    label: '下横排文字',
    section: '文本内容',
    kind: 'text',
    placeholder: '请输入下横排内容',
  },
  {
    key: 'bottomTextFontFamily',
    label: '下横排字体族',
    section: '字体参数',
    kind: 'text',
    placeholder: SONG_FONT,
  },
  {
    key: 'bottomTextFontSizeMm',
    label: '下横排字号(mm)',
    section: '字体参数',
    kind: 'number',
    min: 2,
    max: 10,
    step: 0.1,
  },
  {
    key: 'bottomTextTopFromCenterMm',
    label: '下横排顶距中心(mm)',
    section: '结构参数',
    kind: 'number',
    min: 2,
    max: 16,
    step: 0.1,
    help: '以下横排文字顶部到章面中心线的距离定义。',
  },
]

const codeControls: ControlDefinition[] = [
  {
    key: 'codeText',
    label: '印章编码',
    section: '文本内容',
    kind: 'text',
    placeholder: '13位数字编码',
    help: '默认按规范使用 13 位备案编码。',
  },
  {
    key: 'codeFontFamily',
    label: '编码字体族',
    section: '字体参数',
    kind: 'text',
    placeholder: ARIAL_FONT,
  },
  {
    key: 'codeFontSizeMm',
    label: '编码字号(mm)',
    section: '字体参数',
    kind: 'number',
    min: 0.8,
    max: 4,
    step: 0.1,
  },
  {
    key: 'codeLetterSpacingMm',
    label: '编码字距(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0,
    max: 3,
    step: 0.1,
  },
  {
    key: 'codeBottomMarginMm',
    label: '编码底距(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0.2,
    max: 6,
    step: 0.1,
  },
]

const invoiceCenterControls: ControlDefinition[] = [
  {
    key: 'middleText',
    label: '统一社会信用代码',
    section: '文本内容',
    kind: 'text',
    placeholder: '18位统一社会信用代码',
  },
  {
    key: 'middleTextFontFamily',
    label: '中部字体族',
    section: '字体参数',
    kind: 'text',
    placeholder: ARIAL_FONT,
  },
  {
    key: 'middleTextFontSizeMm',
    label: '中部字号(mm)',
    section: '字体参数',
    kind: 'number',
    min: 2,
    max: 6,
    step: 0.1,
  },
  {
    key: 'middleTextLetterSpacingMm',
    label: '中部字距(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0,
    max: 2,
    step: 0.1,
  },
  {
    key: 'middleTextWidthMm',
    label: '中部总宽(mm)',
    section: '结构参数',
    kind: 'number',
    min: 12,
    max: 32,
    step: 0.1,
  },
  {
    key: 'middleTextOffsetYMm',
    label: '中部纵向偏移(mm)',
    section: '结构参数',
    kind: 'number',
    min: -6,
    max: 6,
    step: 0.1,
  },
  {
    key: 'serialText',
    label: '下方编号',
    section: '文本内容',
    kind: 'text',
    placeholder: '(1)',
  },
  {
    key: 'serialFontFamily',
    label: '编号字体族',
    section: '字体参数',
    kind: 'text',
    placeholder: ARIAL_FONT,
  },
  {
    key: 'serialFontSizeMm',
    label: '编号字号(mm)',
    section: '字体参数',
    kind: 'number',
    min: 1,
    max: 4,
    step: 0.1,
  },
  {
    key: 'serialLetterSpacingMm',
    label: '编号字距(mm)',
    section: '结构参数',
    kind: 'number',
    min: 0,
    max: 2,
    step: 0.1,
  },
  {
    key: 'serialTopFromCenterMm',
    label: '编号顶距中心(mm)',
    section: '结构参数',
    kind: 'number',
    min: 4,
    max: 14,
    step: 0.1,
  },
]

/** 返回指定模板的可编辑控件列表。 */
function mergeControls(...parts: ControlDefinition[][]): ControlDefinition[] {
  return parts.flat()
}

const commonBaseConfig: Omit<SealConfig, 'widthMm' | 'heightMm' | 'borderWidthMm'> = {
  color: '#cb1b2f',
  exportScale: 18,
  topText: '某某科技有限公司',
  topTextFontFamily: SONG_FONT,
  topTextFontSizeMm: 6.8,
  topTextInsetMm: getSpecTopTextInsetMm(1.5, 6.8, 0.8),
  topTextAngleDeg: 270,
  centerSymbolSizeMm: 14,
  centerSymbolOffsetYMm: 0.5,
  bottomText: '',
  bottomTextFontFamily: SONG_FONT,
  bottomTextFontSizeMm: 6.5,
  bottomTextTopFromCenterMm: 6.1,
  codeText: '1101010000001',
  codeFontFamily: ARIAL_FONT,
  codeFontSizeMm: 1.2,
  codeLetterSpacingMm: getSpecCodeLetterSpacingMm(1.2),
  codeBottomMarginMm: 1,
  middleText: '',
  middleTextFontFamily: ARIAL_FONT,
  middleTextFontSizeMm: 3.7,
  middleTextLetterSpacingMm: 0.15,
  middleTextWidthMm: 26,
  middleTextOffsetYMm: 0,
  serialText: '(1)',
  serialFontFamily: ARIAL_FONT,
  serialFontSizeMm: 2.2,
  serialLetterSpacingMm: 0.15,
  serialTopFromCenterMm: 9,
}

export const templatePresets: Record<TemplateId, TemplatePreset> = {
  official: {
    id: 'official',
    name: '公章',
    summary: '国家机关、企业事业单位、社会团体公章',
    notes: ['圆形外框', '默认直径 45mm', '上环 270°', '中心五角星'],
    shape: 'circle',
    showStar: true,
    showCode: true,
    showBottomText: false,
    showMiddleText: false,
    showSerialText: false,
    defaults: {
      ...commonBaseConfig,
      widthMm: 45,
      heightMm: 45,
      borderWidthMm: 1.5,
      topText: '某某科技有限公司',
      topTextFontSizeMm: 6.8,
      topTextInsetMm: getSpecTopTextInsetMm(1.5, 6.8, 0.8),
      topTextAngleDeg: 270,
      centerSymbolSizeMm: 16,
      centerSymbolOffsetYMm: 0.5,
    },
    controls: mergeControls(baseControls, starControls, codeControls),
  },
  contract: {
    id: 'contract',
    name: '合同章',
    summary: '适用于合同专用章版式',
    notes: ['圆形外框', '默认直径 42mm', '上环 240°', '下横排文字'],
    shape: 'circle',
    showStar: true,
    showCode: true,
    showBottomText: true,
    showMiddleText: false,
    showSerialText: false,
    defaults: {
      ...commonBaseConfig,
      widthMm: 42,
      heightMm: 42,
      borderWidthMm: 1.2,
      topText: '某某科技有限公司',
      topTextFontSizeMm: 6.5,
      topTextInsetMm: getSpecTopTextInsetMm(1.2, 6.5, 0.8),
      topTextAngleDeg: 210,
      centerSymbolSizeMm: 14,
      centerSymbolOffsetYMm: 1.5,
      bottomText: '合同专用章',
      bottomTextFontFamily: SONG_FONT,
      bottomTextFontSizeMm: 6.5,
      bottomTextTopFromCenterMm: 6.1,
    },
    controls: mergeControls(baseControls, starControls, bottomTextControls, codeControls),
  },
  invoice: {
    id: 'invoice',
    name: '发票专用章',
    summary: '符合椭圆形发票章排版结构',
    notes: ['椭圆形 40x30mm', '中部信用代码', '下方可带编号', '仿宋 + Arial'],
    shape: 'ellipse',
    showStar: false,
    showCode: false,
    showBottomText: true,
    showMiddleText: true,
    showSerialText: true,
    defaults: {
      ...commonBaseConfig,
      widthMm: 40,
      heightMm: 30,
      borderWidthMm: 1,
      topText: '某某科技有限公司',
      topTextFontFamily: FANG_SONG_FONT,
      topTextFontSizeMm: 4.2,
      topTextInsetMm: getSpecTopTextInsetMm(1, 4.2, 0.5),
      topTextAngleDeg: 230,
      centerSymbolSizeMm: 0,
      centerSymbolOffsetYMm: 0,
      bottomText: '发票专用章',
      bottomTextFontFamily: FANG_SONG_FONT,
      bottomTextFontSizeMm: 4.6,
      bottomTextTopFromCenterMm: 4.2,
      middleText: '91310000123456789A',
      middleTextFontFamily: ARIAL_FONT,
      middleTextFontSizeMm: 3.7,
      middleTextLetterSpacingMm: 0.1,
      middleTextWidthMm: 26,
      serialText: '(1)',
      serialFontFamily: ARIAL_FONT,
      serialFontSizeMm: 2.2,
      serialLetterSpacingMm: 0.1,
      serialTopFromCenterMm: 9,
    },
    controls: mergeControls(baseControls, bottomTextControls, invoiceCenterControls),
  },
  finance: {
    id: 'finance',
    name: '财务专用章',
    summary: '小尺寸财务专用章版式',
    notes: ['圆形外框', '默认直径 30mm', '上环 240°', '小号五角星与下横排'],
    shape: 'circle',
    showStar: true,
    showCode: true,
    showBottomText: true,
    showMiddleText: false,
    showSerialText: false,
    defaults: {
      ...commonBaseConfig,
      widthMm: 30,
      heightMm: 30,
      borderWidthMm: 0.8,
      topText: '某某科技有限公司',
      topTextFontSizeMm: 4.2,
      topTextInsetMm: getSpecTopTextInsetMm(0.8, 4.2, 0.6),
      topTextAngleDeg: 210,
      centerSymbolSizeMm: 9,
      centerSymbolOffsetYMm: 0.7,
      bottomText: '财务专用章',
      bottomTextFontFamily: SONG_FONT,
      bottomTextFontSizeMm: 4.2,
      bottomTextTopFromCenterMm: 4.2,
      codeFontSizeMm: 1.2,
      codeLetterSpacingMm: getSpecCodeLetterSpacingMm(1.2),
      codeBottomMarginMm: 1,
    },
    controls: mergeControls(baseControls, starControls, bottomTextControls, codeControls),
  },
  department: {
    id: 'department',
    name: '部门章',
    summary: '内设机构、部门公章版式',
    notes: ['圆形外框', '默认直径 42mm', '上环 240°', '下横排部门名称'],
    shape: 'circle',
    showStar: true,
    showCode: true,
    showBottomText: true,
    showMiddleText: false,
    showSerialText: false,
    defaults: {
      ...commonBaseConfig,
      widthMm: 42,
      heightMm: 42,
      borderWidthMm: 1.2,
      topText: '某某科技有限公司',
      topTextFontSizeMm: 6.5,
      topTextInsetMm: getSpecTopTextInsetMm(1.2, 6.5, 0.8),
      topTextAngleDeg: 210,
      centerSymbolSizeMm: 14,
      centerSymbolOffsetYMm: 1.5,
      bottomText: '研发中心',
      bottomTextFontFamily: SONG_FONT,
      bottomTextFontSizeMm: 6.5,
      bottomTextTopFromCenterMm: 5.8,
    },
    controls: mergeControls(baseControls, starControls, bottomTextControls, codeControls),
  },
}

export const templateList = Object.values(templatePresets)

/** 返回模板的默认配置副本，避免直接修改常量。 */
export function createTemplateConfig(templateId: TemplateId): SealConfig {
  return { ...templatePresets[templateId].defaults }
}
